version: '3'

services:
  nodejs-app:
    image: nodejs-app:latest
    container_name: nodejs-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - bridge-network
    environment:
      BUCKET_NAME: 'backend-api'
      DB_HOST: '85.95.231.92'
      DB_NAME: 'ondergrup_iot'
      DB_PASS: 'onderadmin1456'
      DB_PORT: '3306'
      DB_USER: 'root'
      EMAIL_SUBJECT: 'Doğrulama Kodunuz!'
      JWT_REFRESH_SECRET: 'onder-backend-api-secret_refresh_%23JSHUJ776X$'
      JWT_SECRET: 'onder-backend-api-secret_%23JSHUJ776X$'
      MINIO_ACCESS_KEY: 'P83jLrCv2pWsE18XQpCO'
      MINIO_ENDPOINT: '85.95.231.92'
      MINIO_PORT: '9099'
      MINIO_SECRET_KEY: 'o3jLtjbth7JRo2HHnG0rIrfBedqRWBpbPLiIIdr2'
      PORT: '3000'
      SMTP_HOST: 'mail.hidirektor.com.tr'
      SMTP_PASS: 'Jjc4FA{{GIEn'
      SMTP_PORT: '587'
      SMTP_USER: 'verification@hidirektor.com.tr'

networks:
  bridge-network:
    driver: bridge